"""sync_recent_changes

Revision ID: 6b8644099361
Revises: dd809f84a535
Create Date: 2026-05-16 04:47:34.052186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b8644099361'
down_revision: Union[str, Sequence[str], None] = 'dd809f84a535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'policies', 'projects', ['project_id'], ['id'], source_schema='user_data', referent_schema='user_data')
    op.add_column('projects', sa.Column('alert_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='user_data')
    op.add_column('projects', sa.Column('deny_alert_threshold', sa.Integer(), server_default='5', nullable=False), schema='user_data')
    op.add_column('projects', sa.Column('deny_alert_window', sa.Integer(), server_default='60', nullable=False), schema='user_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deny_alert_window', schema='user_data')
    op.drop_column('projects', 'deny_alert_threshold', schema='user_data')
    op.drop_column('projects', 'alert_email', schema='user_data')
    op.drop_constraint(None, 'policies', schema='user_data', type_='foreignkey')
    # ### end Alembic commands ###
