"""initial_migration

Revision ID: dd809f84a535
Revises: 
Create Date: 2026-05-14 13:30:03.186276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd809f84a535'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Sanitized: Removed all dangerous drops to internal Supabase schemas.
    # This migration now only ensures your user_data schema is initialized.
    
    # If the tables don't exist, we should create them here.
    # Since they likely exist already from create_all, we'll just ensure columns are present.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
